# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:/flood_map_dialog_base.ui'
#
# Created: Mon May 20 15:51:44 2019
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FloodMapDialogBase(object):
    def setupUi(self, FloodMapDialogBase):
        FloodMapDialogBase.setObjectName(_fromUtf8("FloodMapDialogBase"))
        FloodMapDialogBase.resize(662, 509)
        self.groupBox = QtGui.QGroupBox(FloodMapDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 641, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.txtFilemax = QtGui.QLineEdit(self.groupBox)
        self.txtFilemax.setGeometry(QtCore.QRect(160, 30, 371, 20))
        self.txtFilemax.setObjectName(_fromUtf8("txtFilemax"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(540, 30, 81, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.btnMatcat = QtGui.QPushButton(self.groupBox)
        self.btnMatcat.setGeometry(QtCore.QRect(540, 60, 81, 23))
        self.btnMatcat.setObjectName(_fromUtf8("btnMatcat"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.txtToado = QtGui.QLineEdit(self.groupBox)
        self.txtToado.setGeometry(QtCore.QRect(160, 60, 371, 20))
        self.txtToado.setObjectName(_fromUtf8("txtToado"))
        self.groupBox_2 = QtGui.QGroupBox(FloodMapDialogBase)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 250, 641, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.txtRanhgioi = QtGui.QLineEdit(self.groupBox_2)
        self.txtRanhgioi.setGeometry(QtCore.QRect(160, 30, 371, 20))
        self.txtRanhgioi.setObjectName(_fromUtf8("txtRanhgioi"))
        self.btnRanhgioi = QtGui.QPushButton(self.groupBox_2)
        self.btnRanhgioi.setGeometry(QtCore.QRect(540, 30, 81, 23))
        self.btnRanhgioi.setObjectName(_fromUtf8("btnRanhgioi"))
        self.btnOpenDEM = QtGui.QPushButton(self.groupBox_2)
        self.btnOpenDEM.setGeometry(QtCore.QRect(540, 60, 81, 23))
        self.btnOpenDEM.setObjectName(_fromUtf8("btnOpenDEM"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.txtDem = QtGui.QLineEdit(self.groupBox_2)
        self.txtDem.setGeometry(QtCore.QRect(160, 60, 371, 20))
        self.txtDem.setObjectName(_fromUtf8("txtDem"))
        self.groupBox_3 = QtGui.QGroupBox(FloodMapDialogBase)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 350, 641, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.txtThumuc = QtGui.QLineEdit(self.groupBox_3)
        self.txtThumuc.setGeometry(QtCore.QRect(160, 30, 371, 20))
        self.txtThumuc.setObjectName(_fromUtf8("txtThumuc"))
        self.btnThumuc = QtGui.QPushButton(self.groupBox_3)
        self.btnThumuc.setGeometry(QtCore.QRect(540, 30, 81, 23))
        self.btnThumuc.setObjectName(_fromUtf8("btnThumuc"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(540, 60, 81, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 60, 371, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.groupBox_4 = QtGui.QGroupBox(FloodMapDialogBase)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 110, 641, 131))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.txtFileGio = QtGui.QLineEdit(self.groupBox_4)
        self.txtFileGio.setGeometry(QtCore.QRect(160, 30, 371, 20))
        self.txtFileGio.setObjectName(_fromUtf8("txtFileGio"))
        self.btnNgapGio = QtGui.QPushButton(self.groupBox_4)
        self.btnNgapGio.setGeometry(QtCore.QRect(540, 30, 81, 23))
        self.btnNgapGio.setObjectName(_fromUtf8("btnNgapGio"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 131, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.cboNgaybatdau = QtGui.QComboBox(self.groupBox_4)
        self.cboNgaybatdau.setGeometry(QtCore.QRect(160, 60, 181, 22))
        self.cboNgaybatdau.setObjectName(_fromUtf8("cboNgaybatdau"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(380, 90, 71, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(450, 90, 81, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.spinBox = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox.setGeometry(QtCore.QRect(160, 90, 181, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.groupBox_5 = QtGui.QGroupBox(FloodMapDialogBase)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 450, 641, 51))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.button_box = QtGui.QDialogButtonBox(self.groupBox_5)
        self.button_box.setGeometry(QtCore.QRect(460, 10, 161, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.btnNapDl = QtGui.QPushButton(self.groupBox_5)
        self.btnNapDl.setGeometry(QtCore.QRect(10, 14, 75, 23))
        self.btnNapDl.setObjectName(_fromUtf8("btnNapDl"))
        self.btnNoisuy = QtGui.QPushButton(self.groupBox_5)
        self.btnNoisuy.setGeometry(QtCore.QRect(100, 14, 101, 23))
        self.btnNoisuy.setObjectName(_fromUtf8("btnNoisuy"))
        self.btnTaobd = QtGui.QPushButton(self.groupBox_5)
        self.btnTaobd.setGeometry(QtCore.QRect(210, 14, 101, 23))
        self.btnTaobd.setObjectName(_fromUtf8("btnTaobd"))
        self.btnTaobd_2 = QtGui.QPushButton(self.groupBox_5)
        self.btnTaobd_2.setGeometry(QtCore.QRect(320, 14, 101, 23))
        self.btnTaobd_2.setObjectName(_fromUtf8("btnTaobd_2"))

        self.retranslateUi(FloodMapDialogBase)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), FloodMapDialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), FloodMapDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(FloodMapDialogBase)

    def retranslateUi(self, FloodMapDialogBase):
        FloodMapDialogBase.setWindowTitle(_translate("FloodMapDialogBase", "Xây dựng bản đồ ngập lũ ", None))
        self.groupBox.setTitle(_translate("FloodMapDialogBase", "Dữ liệu ngập cao nhất từ DeltaP", None))
        self.label.setText(_translate("FloodMapDialogBase", "Tên file dữ liệu ngập cao nhất", None))
        self.pushButton.setText(_translate("FloodMapDialogBase", "Chọn file", None))
        self.btnMatcat.setText(_translate("FloodMapDialogBase", "Chọn file", None))
        self.label_2.setText(_translate("FloodMapDialogBase", "File tọa độ mặt cắt", None))
        self.groupBox_2.setTitle(_translate("FloodMapDialogBase", "Thông tin vùng thành lập bản đồ", None))
        self.label_3.setText(_translate("FloodMapDialogBase", "Bản đồ vùng bao", None))
        self.btnRanhgioi.setText(_translate("FloodMapDialogBase", "Chọn file", None))
        self.btnOpenDEM.setText(_translate("FloodMapDialogBase", "Chọn file", None))
        self.label_4.setText(_translate("FloodMapDialogBase", "Lớp DEM", None))
        self.groupBox_3.setTitle(_translate("FloodMapDialogBase", "Kết quả xây dựng bản đồ", None))
        self.label_5.setText(_translate("FloodMapDialogBase", "Thư mục chứa kết quả", None))
        self.btnThumuc.setText(_translate("FloodMapDialogBase", "Chọn thư mục", None))
        self.pushButton_6.setText(_translate("FloodMapDialogBase", "Chọn file", None))
        self.label_6.setText(_translate("FloodMapDialogBase", "Đặt tên file dự án QGIS lưu", None))
        self.groupBox_4.setTitle(_translate("FloodMapDialogBase", "Dữ liệu ngập theo giờ", None))
        self.btnNgapGio.setText(_translate("FloodMapDialogBase", "Chọn file", None))
        self.label_8.setText(_translate("FloodMapDialogBase", "Thời gian bắt đầu chọn", None))
        self.label_9.setText(_translate("FloodMapDialogBase", "File dữ liệu ngập theo giờ", None))
        self.label_10.setText(_translate("FloodMapDialogBase", "Bước nhảy thời gian (giờ)", None))
        self.label_11.setText(_translate("FloodMapDialogBase", "Số giờ chọn", None))
        self.btnNapDl.setText(_translate("FloodMapDialogBase", "Nạp dữ liệu", None))
        self.btnNoisuy.setText(_translate("FloodMapDialogBase", "Nội suy dữ liệu", None))
        self.btnTaobd.setText(_translate("FloodMapDialogBase", "Tạo bản đồ ngập", None))
        self.btnTaobd_2.setText(_translate("FloodMapDialogBase", "Xuất dữ liệu ngập", None))

